Preview Mode
strapi/strapi-starter-gatsby-corporate pull request #11
Opened 2021-03-31 12:38 UTC by markkaylor

2021-04-01 15:25 UTC, remidej reviewed
Hey, I'm trying it in Firefox but it looks like it doesn't like the way cookies are handled:

> Cookie “strapiPreview” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Also, can you share the formula used to get the URL of preview pages? Is it exactly the same as for Next? It would be nice to have that information in the readme

2021-04-01 15:28 UTC, markkaylor commented
Bummer, should have tested in other browsers.  I'll take a look.  It's not exactly the same, sorry should have sent it.  It's also in the preview.js file but here you go:
```
/**
 * You can preview pages with URLs like this:
 * http://localhost:8000/preview/<slug>?secret=<preview-secret>
 * where <preview-secret> is the PREVIEW_SECRET variable defined in your .env config
 * and <slug> is the slug you entered in Strapi for your page
 */
```

2021-04-01 16:17 UTC, markkaylor commented
@remidej added `secure` and `sameSite` option https://www.npmjs.com/package/react-cookie

2021-04-01 16:38 UTC, remidej reviewed
Thanks, I no longer have the error on firefox

But it looks I can't get the cookies system to work:

- I can see the preview banner, but clicking on "turn off" doesn't remove it
- On a secret page, I no longer see the preview banner. I only see the "you need to turn preview mode on to view this page" message

2021-04-01 16:38 UTC, remidej commented on README.md
>  And for the backend:
I think we should remove the "and for the backend" part, it's no longer used and it's confusing

2021-04-02 07:36 UTC, markkaylor commented
https://user-images.githubusercontent.com/26598053/113393310-c6864d80-9396-11eb-9020-23d0dac97315.mov

2021-04-02 14:36 UTC, remidej requested changes
I can't get it to work yet, but I've added some code recommendations in the meantime :)

2021-04-02 14:36 UTC, remidej commented on starter/src/pages/preview.js
> +import WithLocation from "@/components/with-location"
Same comment as above about useLocation

2021-04-02 14:36 UTC, remidej commented on starter/src/components/sections.js
> +import WithLocation from "@/components/with-location"
Have you tried Reach Router's useLocation hook?

If it works, I think it would be cleaner, and would remove the need for the with-location

2021-04-02 14:36 UTC, remidej commented on starter/src/pages/preview.js
> +        <div>
It would be nice to also use the SEO component here, like on the real pages.

Maybe we can prefix the page titles with "Preview" or something like this

2021-04-02 14:36 UTC, remidej commented on starter/src/components/sections.js
> +            navigate("/", { state: { prevPath: location.pathname } })
Shouldn't this clear the cookie?

2021-04-02 14:36 UTC, remidej commented on starter/src/pages/preview.js
> +      secure: process.env.NODE_ENV === 'production' ? true : false,
I believe ou can remove the `true : false` here

2021-04-02 14:36 UTC, remidej commented on starter/src/pages/preview.js
> +      const [data] = await fetchAPI(`/pages?slug=${slug}&status=draft`)
That's a clever way to fetch the first item 😁

2021-04-02 14:36 UTC, remidej commented on starter/package.json
> +    "query-string": "^7.0.0",
I think we can use [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) to avoid having too many dependencies

2021-04-02 14:36 UTC, remidej commented on starter/package.json
> +    "http-proxy-middleware": "^1.0.6",
Is this used?

2021-04-02 14:36 UTC, remidej commented on starter/package.json
> +    "universal-cookie": "^4.0.4",
Looks like this one can be removed since you're using react-cookie

2021-04-02 14:49 UTC, markkaylor commented on starter/src/pages/preview.js
> +      secure: process.env.NODE_ENV === 'production' ? true : false,
haha 🤦 yes

2021-04-02 14:52 UTC, markkaylor commented on starter/src/components/sections.js
> +            navigate("/", { state: { prevPath: location.pathname } })
Originally that is what I was doing.  But there is an issue if you are on the preview page and you click the turn off button, then it deletes the cookie _and_ then sets the cookie.  Not really sure why because I was navigating then deleting 🤷‍♂️ .  I struggled with this for a while, and the useEffect I'm using below was the best I could do.  If you can think of anything else I'm open to suggestions :)

2021-04-02 14:53 UTC, markkaylor commented on starter/package.json
> +    "http-proxy-middleware": "^1.0.6",
nope, needs to be removed.  Thanks.

2021-04-06 09:04 UTC, markkaylor commented on starter/src/pages/preview.js
> +        <div>
I went ahead and added it, but curious what are the SEO benefits of draft pages?  I actually removed the component because I thought these are pages I don't want search engines to crawl...

2021-04-07 13:41 UTC, remidej requested changes
Just a couple things left :)

2021-04-07 13:41 UTC, remidej commented on starter/src/components/sections.js
> +// TODO: Use single map for draft and published content
I think we can leave it like this for now, since it will change once we start using the source strapi plugin. But we can probably remove that comment

2021-04-07 13:41 UTC, remidej commented on starter/src/pages/preview.js
> +      const [data] = await fetchAPI(`/pages?slug=${slug}&status=draft`)
I think we can remove the status filter altogether. This way it wouldn't break if we enter a non-secret page

2021-04-07 13:56 UTC, markkaylor commented on starter/src/components/sections.js
> +// TODO: Use single map for draft and published content
sounds good will do 👍

2021-04-07 15:27 UTC, remidej approved these changes
Looks good to me

2021-04-08 07:22 UTC, merged