I18n
strapi/strapi-starter-gatsby-corporate pull request #14
Opened 2021-05-10 07:33 UTC by markkaylor

2021-05-12 08:39 UTC, markkaylor commented on starter/src/utils/localize.js
> +  return localizedPaths
🤷‍♂️

2021-05-14 15:35 UTC, remidej requested changes

2021-05-14 15:37 UTC, remidej commented on starter/src/utils/localize.js
> +      const page = { ...pageContext, ...localePage }
I really like this

2021-05-14 15:50 UTC, remidej commented on starter/src/utils/localize.js
> +  return localizedPaths
Line 59 was a bit confusing to me, but it looks like it works

2021-05-19 17:21 UTC, remidej approved these changes
Everything looks good to me here too!

But just like for Next, let's wait for the template changes to be ready before we merge this

2021-05-21 08:44 UTC, merged